### ISSUE TITLE
Crashes when click bookmarks-sidebar icon in side of chrome://extensions

### ISSUE THREAD

**Issue by ryumiel** [ltilve/chromium#11]

**Comment by ltilve** [comment]
I have been able to reproduce the crash not on chrome://extensions, but when unclicking an extension that was showing its sidebar, in particular, with extension https://github.com/ltilve/demo-extensions/tree/master/process_monitor-3 at commit 9c555b7b0b4ef5c3 on yoon-browserAction http://pastebin.com/04iNptpw

**Comment by ryumiel** [comment]
Fix was pushed at d060243d6c6e50f70cdd592dff65fb58d90d8b08, if the linux port passes the scenario, we can close this issue

**Comment by ltilve** [comment]
It's not being reproducible on Linux either.
