### ISSUE TITLE
Restrict width of sidebar

### ISSUE THREAD

**Issue by ryumiel** [ltilve/chromium#13]
Implement proper codes instead of hard coded value with comment:

void BrowserView::UpdateSidebarForContents(content::WebContents\* new_contents) {
...
    int sidebar_width = 300;// g_browser_process->local_state()->GetInteger(
        //prefs::kExtensionSidebarWidth);

**Comment by ltilve** [comment]
Fixed for Linux port at https://github.com/ltilve/chromium/commit/3c23a23cde5250e669b265907f76702afe03b92d Rigth now the Mac port is limiting the minimum sidebar width to 50px, not sure if is a desirable restriction.

**Comment by ryumiel** [comment]
I think we need to apply same restriction with linux port. I'll update Mac side UI tomorrow.

**Comment by benmccann** [comment]
We'd like to be able to have the width go to 0.  But we should have a maximum width

**Comment by ltilve** [comment]
Now the sidebar view is created with a default 1/7 of the available total width, and the maximum value that can be used for kExtensionSidebarWidth is 1/2. The user can resize it up and down, but when closing and restoring  sidebars it will never exceed that 50%.

**Comment by ryumiel** [comment]
50px minimum width restriction of sidebar in Mac was completely removed at 6bfaea830481b6141a13ae67c8ce70c1e4fb5d6b
