### ISSUE TITLE
Crash after rebasing at interactive_ui_tests 

### ISSUE THREAD

**Issue by ryumiel** [ltilve/chromium#16]
- out/Debug/interactive_ui_tests --no-sandbox --single_process --gtest_filter=SidebarTest.*

Crashes at SidebarTest::ShowSidebar(WebContents\* temp, const std::string& test_page),
Due to the null host_ in SidebarContainer.
We need to check initialization sequence of SidebarContainer and SidebarManager

**Comment by ryumiel** [comment]
Unable to find Extension\* from ExtensionSet::GetByID

const Extension\* ExtensionSet::GetByID(const std::string& id) const {
  ExtensionMap::const_iterator i = extensions_.find(id);
  if (i != extensions_.end())
    return i->second.get();
  else
    return NULL;
}

**Comment by ryumiel** [comment]
Wrong extension_id at const Extension\* GetExtensionForUrl(Profile\* profile, const GURL& url)
causes NULL extension

Expected

Name : extension_id
    Details:{static npos = 18446744073709551615, _M_dataplus = {std::allocator<char> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x1eacbe188b98 "ncgnpfebcfncmafojeeknfilnahcakfe"}}

Actual:

Name : extension_id
    Details:{static npos = 18446744073709551615, _M_dataplus = {std::allocator<char> = {<__gnu_cxx::new_allocator<char>> = {<No data fields>}, <No data fields>}, _M_p = 0x3d3e71555758 "127.0.0.1"}}

**Comment by ryumiel** [comment]
ExtensionViewHost tries to load extension but if we passes empty or invalid url, it refuses to load

It looks like we have to use TestExtensionDir and load extension inside of that to generate proper extension for test.

That's quite interesting that we already have content_id_ in sidebar_browsertest
but we construct ExtensionViewHost using just URL, content_id_ only used for managing extensions inside of sidebar_manager.

To follow convention in ExtensionViewHost, we should use same scheme with other extensions like popup or dialog.

**Comment by ltilve** [comment]
Fixed at https://github.com/ltilve/chromium/commit/52812d07634a3d30ad732ec96cd388f53e45d952
