### ISSUE TITLE
Consider avoiding NOTIFICATION_SIDEBAR_CHANGED

### ISSUE THREAD

**Issue by ltilve** [ltilve/chromium#18]
By https://codereview.chromium.org/1152613003/diff/20001/chrome/browser/chrome_notification_types.h#newcode343

> We're working "hard" (read: we really want to, but bandwidth is hard to come by)
> to deprecate notifications, so it'd be best to avoid adding any more, if we can.

**Comment by ryumiel** [comment]
It is removed from Mac port by 39964ab39d67bf87d1d44b5c9035a2cb578a1a33

**Comment by ltilve** [comment]
It has been possible to replace the usage of a notification for the sidebar change at https://github.com/ltilve/chromium/commit/606ffb56d780a448b38fe8b1a44520c227c788a6
