### ISSUE TITLE
Assertion failures when opening / closing sidebar in debug mode

### ISSUE THREAD

**Issue by ryumiel** [ltilve/chromium#30]
AddObserver should be done at construction time of ExtensionActionViewController,
to match with RemoveObserver in destructor of ExtensionActionViewController.
So we need to remove AddObserver from TriggerPopupWithUrl

It is handled at cd41a1e0c4f461d01b75a5ec425eab20787bbf10

Also, We need to handle popup_owner_  of ToolbarActionBar properly.

**Comment by ltilve** [comment]
https://github.com/ltilve/chromium/commit/90915d231aadf0d9974d7e2c0e910234c4f7b46a and  https://github.com/ltilve/chromium/commit/a85c9431371a293fc063b5ec84321a9040a02cd3 Merged with the rest of the refactoring
