### ISSUE TITLE
Fix comments on overflown issues and is_showing_sidebar() changes

### ISSUE THREAD

**Issue by ltilve** [ltilve/chromium#33]
Fixing addressed reviews at https://codereview.chromium.org/1168383002/#msg13

**Comment by ltilve** [comment]
The following commits fix the initial comments wrt the tests and overflow behaviour https://github.com/ltilve/chromium/commit/f2949bff8e7555b547d35c8748baed8216947918 https://github.com/ltilve/chromium/commit/0f400768b68dbf186ccd8a744cebeef7bb430dd4

**Comment by ryumiel** [comment]
Change about refactoring is uploaded at 605ddfebb24719dbcaa13afe4dcf536a33c4e994
(including is_showing_sidebar)

**Comment by ryumiel** [comment]
As mentioned in below commit, is_showing_sidebar_ was reverted.
e97b374c3de386d45d57e279faf7870fce8a75f6

Now we are ready to send a CL

**Comment by ltilve** [comment]
All the comments have been handled and pushed https://codereview.chromium.org/1168383002/#msg14
