### ISSUE TITLE
Do not close popup when click other extension button to close sidebar.

### ISSUE THREAD

**Issue by ryumiel** [ltilve/chromium#34]

**Comment by ryumiel** [comment]
I'm not sure whether is it a desired behavior or not.

**Comment by ltilve** [comment]
Popups should be closed when the user clicks anywhere else. If the click is to open/close any other sidebar or extension, the behaviour should be the same IMO.

**Comment by ryumiel** [comment]
I agree that we don't have a reason to change this behavior.
