### ISSUE TITLE
Additional refactoring extension_action_view_controller and evaluate removal of sidebarContainer

### ISSUE THREAD

**Issue by ltilve** [ltilve/chromium#39]

**Comment by ryumiel** [comment]
Refactoring had done.
Patches are updated to sidebar-action-yoon and sidebar-cocoa-yoon respectively.

At sidebar-action-yoon
@ryumiel
ps11: Fix assertion Failure of BrowserActionsBarBrowserTest.BrowserAc… …
ryumiel authored 12 days ago
42d30cb  
@ryumiel
ps11: Remove sidebar_container …
ryumiel authored an hour ago
d05c2df  
@ryumiel
ps11: Add accidently omitted closure execution at sidebar case. …
ryumiel authored 5 hours ago
d162c30  
@ryumiel
ps11: Clean up ExtensionActionViewController::HideActiveSidebar …
ryumiel authored 5 hours ago
782511e  

at sidebar-cocoa-yoon
@ryumiel
ps11: Remove unused header from browser_view.cc
ryumiel authored an hour ago
6a5b32d
