### ISSUE TITLE
Crash with page_action popups on old toolbar design

### ISSUE THREAD

**Issue by ltilve** [ltilve/chromium#40]
When the new toolbar design is not enabled at chrome://flags/#enable-extension-action-redesign, closing the popup of a page-action extension (for instance this, that shows a clickable pageaction when the url contains a 'g' http://people.igalia.com/ltilve/pageaction_by_url.tgz), crashes the browser.

**Comment by ryumiel** [comment]
Fixed at 7522bccd724ce99912f9c5af595a122d8f169390
