### ISSUE TITLE
Enable unit test in browserAction CL

### ISSUE THREAD

**Issue by ryumiel** [ltilve/chromium#6]

**Comment by ltilve** [comment]
Some of the necessary files for running the unit tests for browserAction (test/data/sidebar/manifest.json and test/data/sidebar/simple_page.html) had been commited on the corresponding API part at https://github.com/ltilve/chromium/commit/8633a380d1b251fea7d4a879a5a0b68cdc694cfb and the manifest was not being properly specified.

**Comment by ltilve** [comment]
Squashing the corresponding FIXUP https://github.com/ltilve/chromium/commit/f21d51b36fb4c4b438d58d8e9687e07b7df8888c into the browserAction CL, the 4 unit tests are properly passing.

```
~/chromium/src/out/Release/interactive_ui_tests --gtest_filter=SidebarTest.*

[1/4] SidebarTest.OpenClose (1571 ms)
[2/4] SidebarTest.SwitchingTabs (782 ms)
[3/4] SidebarTest.SidebarOnInactiveTab (782 ms)
[4/4] SidebarTest.SidebarNavigate (1306 ms)
SUCCESS: all tests passed.
```
